### PR TITLE
Update node install step to version 16

### PR DESCRIPTION
**Pull request by jvoll**
## Summary:
A couple weeks ago we upgraded from version 12 to 16. 12 no longers works.

Issue: none

## Test plan:
yolo

### CODE REVIEW

**Comment by somewhatabstract** [comment]
Hmmm 12 should still work. Where are you seeing that it no longer works?

**Comment by somewhatabstract** [comment]
I should add I don't mind us updating the dot files. It needs to be done. Just concerned by the "Node 12 no longer works" comment as that certainly should not be the case.

**Comment by jvoll** [comment]
You beat me to it! We realized that maybe this is _not_ mandatory but feel free to commandeer this PR when it is time.

@jeremywiebe and I were trying to get my dev server up and running on my new M1 MBP and had an issue with my node install. We believe the issue was that I had node 12 for arm and it was not compatible. By upgrading to 16 we ended up installing the x86 version of node 16 and thus it fixed the issue.

**Comment by jvoll** [comment]
I'll leave it up to @dbraley as to if we want to merge this PR right now or hold off a bit!

@somewhatabstract I think this means I've joined your Node 16 beta group as that is now what is running on my machine 😂

**Comment by dbraley** [comment]
I suspect node 12 may have to do with trying to run it without rosetta, but i'm not sure. Will discuss this with @jeremywiebe in a bit.

**Review by somewhatabstract — APPROVED** [review]
This change looks good to me. I think having all new folks be on Node 16 makes sense given everyone will be soon. Also, Node 16 is the first build of Node 16 that's native for M1 so that'll be nice for M1 folks :)

**Comment by jvoll** [comment]
@dbraley now that node 16 is the default for all devs should we go ahead and merge this?

**Pull request merged**
