### PR TITLE
Approximate code changes for PostgreSQL 14 update/upgrade.

### PR DESCRIPTION
**Pull request by daelious**
### THIS SHOULD NEVER BE CHECKED INTO MASTER

- Updated the scripts for PostgreSQL 14 instead of 11.
- Genericized the variable names for upgrades in the future.

### CODE REVIEW

**Comment by latteier** [comment]
We normally include a STOPSHIP comment to indicate that a change isn't ready to go into production.

In this case it would be helpful to give some context in the PR about what the purpose of this PR. Is this just for discussion?  Do we expect it to be merged after some upcoming changes? If that's the case you can make the PR a draft to indicate that it's not ready yet.

**Comment by daelious** [comment]
@latteier - Sorry first PR here, do I just add the comment by itself or should it be in the subject line?

**Comment by latteier** [comment]
Thanks for making this PR a draft.

I'm not sure how/if we check for STOPSHIP in this repo, but in webapp you add it as a code comment and linting keeps it from being merged to master.

**Comment by StevenACoffman** [comment]
Hi! We are updating from postgres 11 to 14 in prod, so I would like to resurrect this.

**Pull request closed without merging**
