### PR TITLE
Upgrade go to 1.16

### PR DESCRIPTION
**Pull request by jgervais**
## Summary:
It's that time again. appengine has been fully deployed and is now running
1.16 and now we're on step 2 of https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/949387416/Go+version+upgrades

Issue: https://khanacademy.atlassian.net/browse/INFRA-6907

## Test plan:
I ran it and go version reports I'm on 1.16

### CODE REVIEW

**Review by csilvers — APPROVED** [review]
So exciting!

**Comment by jgervais** [comment]
@yogieric I'm not sure if we want to do this because we don't differentiate between intel and m1 in these scripts currently. Your thoughts here would be appricated.

**Comment by csilvers** [comment]
> @yogieric I'm not sure if we want to do this because we don't differentiate between intel and m1 in these scripts currently. Your thoughts here would be appricated.

My understanding is that 1.15 is also broken on M1, so this doesn't make things any worse.  M1 users have to use 1.17.

**Comment by yogieric** [comment]
1.15 works just fine on M1s if you follow the steps outlined in https://khanacademy.atlassian.net/wiki/spaces/INFRA/pages/1201864735/Setting+up+khan-dotfiles

It runs under rosetta which is suboptimal, but is maybe noticeable, maybe not. 

When we move to 1.16, the wiki page above needs to be updated. And, ideally, somebody would verify following the instructions there works both for clean installs and for updates.

@dbraley is planning to test some local devenv stuff soon and can probably easily verify much of this.

**Review by dbraley — APPROVED** [review]
Tested on Big Sur and Monterey on Intel. Will test on M1 when I get a chance, but no reason to believe it won't work and no reason to hold this up even if it doesn't. :shipit:

**Pull request closed without merging**
