### PR TITLE
Make sure we install docker, and set it up with gcloud.

### PR DESCRIPTION
**Pull request by csilvers**
## Summary:
This is needed to run devserver locally in containers.

Note that this PR does not install docker-compose, or docker
desktop/docker ranch, or some other higher-level docker stuff that
devserver will need.  That will happen in a later PR.

Issue: https://khanacademy.slack.com/archives/C04LASC76G6/p1695236711905889

## Test plan:
Ran the gcloud command manually.  Will need help to test the mac command.

### CODE REVIEW

**Review by jenglund — APPROVED** [review]
Looks great, and thank you for updating the comments to include that context about the dev server! 👍

**Review by jenglund — APPROVED** [review]

**Review by dbraley — APPROVED** [review]
This should work. I need to uninstall desktop before I can try it I think though. It doesn't seem to cause problems for me, though so I suspect it's fine!

**Comment by latteier** [comment]
If you install desktop docker that it includes the cli. So I don't think that we need to brew install docker on mac. Though hopefully it doesn't cause any conflicts when installing desktop docker (or rancher or whatever) later on.

**Comment by csilvers** [comment]
> If you install desktop docker it includes the cli. So I don't think that we need to brew install docker on mac. Though hopefully it doesn't cause any conflicts when installing desktop docker (or rancher or whatever) later on.

Right, my worry is that `gcloud docker auth` won't work if docker isn't installed, so I want to install it for that.  I'll add a TODO about the UI.

**Pull request merged**
